locations:
  - Pacific Palisades
  - Malibu
  - Topanga Canyon
  - Pacific Coast Highway
  - PCH
  - Sunset Boulevard
  - Santa Monica Mountains
  - Temescal Canyon
  - Brentwood
  - Santa Monica
  - Calabasas
  - Will Rogers State Park
  - Getty Villa
  - Pepperdine
